[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.163"
serde_derive = "1.0.166"
toml = "0.7.1"
serde_json = "1.0.99"
rand = "0.8.5"